List<String> getLyrics() {
  return [
    'Pom!',
    'Polopo pom',
    'Polop!',
    'Pom!',
    'Polopo pom',
    'Polop!',
    'Pom!',
    'Polopopom pom!',
    'Polop!',
    'Pom!',
    'Polopopom!',
    'Polopopom',
    'Dreaming, at the airport',
    'I wanna fly with you',
    'Dreaming, at the airport',
    'Fly with you',
    'I wanna fly with you',
    'Pom!',
    'Polopopom pom!',
    'Polop!',
    'Pom!',
    'Polopopom!',
    'Polopopom',
    'Dreaming, at the airport',
    'I wanna fly with you',
    'Dreaming, at the airport',
    'Fly with you',
    'I wanna fly with you, my little girl',
    'Pom!',
    'Polopopom pom!',
    'Polop!',
    'Pom!',
    'Polopopom!',
    'Polopopom',
    'Dreaming, at the airport',
    'I wanna fly with you',
    'Dreaming, at the airport',
    'Fly with you',
    'I wanna fly with you, my little girl',
  ];
}
